---
# tasks file for db
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Change mongo config file
  template:
    src: mongod.conf.j2 # <-- Путь до локального файла-шаблона
    dest: /etc/mongod.conf # <-- Путь на удаленном хосте
    mode: 0644 # <-- Права на файл, которые нужно установить
  notify: restart mongod

- name: Start mongod
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Wait for port opened
  wait_for:
    port: "{{ mongodb_port }}"
