---
- name: deploy app
  become: true
  hosts: app
  tags: deploy-tag
  vars:
    install_dir: /opt/reddit
  tasks:

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "{{ install_dir }}"
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ install_dir }}" # <-- В какой директории выполнить команду bundle

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
