---
- name: deploy app
  become: true
  hosts: app
  tags: deploy-tag
  vars:
    install_dir: /opt/reddit
    deploy_user: ubuntu
  tasks:

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit" # <-- В какой директории выполнить команду bundle

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
