---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

# - name:
#   debug:
#     msg: "{{ hostvars[groups.db[0]]['internal_address'] }}"

- include: ruby.yml
- include: puma.yml

- name: enable puma
  systemd:
    name: puma
    enabled: yes
    daemon_reload: yes
