---
# handlers file for db
- name: restart mongod
  become: true
  service:
    name: mongod
    state: restarted
    daemon_reload: yes

- name: start_mongodb
  systemd:
    name: mongod
    enabled: yes
    daemon_reload: yes
    state: started

- name: restart_mongodb
  systemd:
    name: mongod
    enabled: yes
    daemon_reload: yes
    state: restarted
