---
- name: Configure app
  hosts: app
  vars:
    db_host: 10.17.100.8
  become: true
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /opt/db_config

    - name: enable puma

      systemd:
        name: puma
        enabled: yes
        daemon_reload: yes
  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
