---
- name: Configure MongoDB on DB host
  become: true
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      become: true # <-- Выполнить задание от root
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: 0644 # <-- Права на файл, которые нужно установить
      notify: restart mongod

  handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service:
        name: mongod
        state: restarted
        daemon_reload: yes
