---
- name: Configure hosts & deploy application
  become: true
  hosts: all
  vars:
    - mongo_bind_ip: 0.0.0.0
    - db_host: 10.17.100.25
    - install_dir: /opt/reddit
  tasks:

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "{{ install_dir }}"
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ install_dir }}" # <-- В какой директории выполнить команду bundle
      tags: deploy-tag


    - name: Change mongo config file
      become: true # <-- Выполнить задание от root
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: 0644 # <-- Права на файл, которые нужно установить
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /opt/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd:
        name: puma
        enabled: yes
        daemon_reload: yes
      tags: app-tag



  handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service:
        name: mongod
        state: restarted
        daemon_reload: yes

    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
